apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-creds
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    name: postgres-creds
  data:
    - secretKey: dbpassword
      remoteRef:
        key: keycloak-postgres-password   # The name in Azure for the KEY